advancement-rewards:
  task: 10
  goal: 25
  challenge: 100
  exceptions:
    end/kill_dragon: 500
    nether/summon_wither: 300

shop:
  ui:
    filler:
      material: GRAY_STAINED_GLASS_PANE
      name: " "
    main:
      size: 27
      title: "&2Rewards Shop"
      books-slot: 11
      books-name: "&dEnchanted Books"
      player-slot: 4
      equipment-slot: 15
      equipment-name: "&bCustom Equipment"
    category:
      back-slot: 53
    books:
      size: 54
      title: "&2Enchanted Books"
    equipment:
      size: 27
      title: "&2Custom Equipment"
  items:
    efficiency-6:
      slot: 10
      name: "Efficiency VI"
      icon: ENCHANTED_BOOK
      points: 100
      requirements:
        - "1x Enchanted Book (Efficiency V)"
      required-items:
        - ENCHANTED_BOOK:1:EFFICIENCY:5
      reward:
        material: ENCHANTED_BOOK
        name: "Efficiency VI"
        enchants:
          - EFFICIENCY:6
    unbreaking-4:
      slot: 11
      name: "Unbreaking IV"
      icon: ENCHANTED_BOOK
      points: 100
      requirements:
        - "1x Enchanted Book (Unbreaking III)"
      required-items:
        - ENCHANTED_BOOK:1:UNBREAKING:3
      reward:
        material: ENCHANTED_BOOK
        name: "Unbreaking IV"
        enchants:
          - UNBREAKING:4
    protection-5:
      slot: 12
      name: "Protection V"
      icon: ENCHANTED_BOOK
      points: 120
      requirements:
        - "1x Enchanted Book (Protection IV)"
      required-items:
        - ENCHANTED_BOOK:1:PROTECTION:4
      reward:
        material: ENCHANTED_BOOK
        name: "Protection V"
        enchants:
          - PROTECTION:5
    sharpness-6:
      slot: 13
      name: "Sharpness VI"
      icon: ENCHANTED_BOOK
      points: 120
      requirements:
        - "1x Enchanted Book (Sharpness V)"
      required-items:
        - ENCHANTED_BOOK:1:SHARPNESS:5
      reward:
        material: ENCHANTED_BOOK
        name: "Sharpness VI"
        enchants:
          - SHARPNESS:6
    fire-protection-5:
      name: "Fire Protection V"
      icon: ENCHANTED_BOOK
      points: 100
      requirements:
        - "1x Enchanted Book (Fire Protection IV)"
      required-items:
        - ENCHANTED_BOOK:1:FIRE_PROTECTION:4
      reward:
        material: ENCHANTED_BOOK
        name: "Fire Protection V"
        enchants:
          - FIRE_PROTECTION:5
    feather-falling-5:
      name: "Feather Falling V"
      icon: ENCHANTED_BOOK
      points: 100
      requirements:
        - "1x Enchanted Book (Feather Falling IV)"
      required-items:
        - ENCHANTED_BOOK:1:FEATHER_FALLING:4
      reward:
        material: ENCHANTED_BOOK
        name: "Feather Falling V"
        enchants:
          - FEATHER_FALLING:5
    blast-protection-5:
      name: "Blast Protection V"
      icon: ENCHANTED_BOOK
      points: 100
      requirements:
        - "1x Enchanted Book (Blast Protection IV)"
      required-items:
        - ENCHANTED_BOOK:1:BLAST_PROTECTION:4
      reward:
        material: ENCHANTED_BOOK
        name: "Blast Protection V"
        enchants:
          - BLAST_PROTECTION:5
    projectile-protection-5:
      name: "Projectile Protection V"
      icon: ENCHANTED_BOOK
      points: 100
      requirements:
        - "1x Enchanted Book (Projectile Protection IV)"
      required-items:
        - ENCHANTED_BOOK:1:PROJECTILE_PROTECTION:4
      reward:
        material: ENCHANTED_BOOK
        name: "Projectile Protection V"
        enchants:
          - PROJECTILE_PROTECTION:5
    respiration-4:
      name: "Respiration IV"
      icon: ENCHANTED_BOOK
      points: 100
      requirements:
        - "1x Enchanted Book (Respiration III)"
      required-items:
        - ENCHANTED_BOOK:1:RESPIRATION:3
      reward:
        material: ENCHANTED_BOOK
        name: "Respiration IV"
        enchants:
          - RESPIRATION:4
    depth-strider-4:
      name: "Depth Strider IV"
      icon: ENCHANTED_BOOK
      points: 100
      requirements:
        - "1x Enchanted Book (Depth Strider III)"
      required-items:
        - ENCHANTED_BOOK:1:DEPTH_STRIDER:3
      reward:
        material: ENCHANTED_BOOK
        name: "Depth Strider IV"
        enchants:
          - DEPTH_STRIDER:4
    frost-walker-3:
      name: "Frost Walker III"
      icon: ENCHANTED_BOOK
      points: 100
      requirements:
        - "1x Enchanted Book (Frost Walker II)"
      required-items:
        - ENCHANTED_BOOK:1:FROST_WALKER:2
      reward:
        material: ENCHANTED_BOOK
        name: "Frost Walker III"
        enchants:
          - FROST_WALKER:3
    smite-6:
      name: "Smite VI"
      icon: ENCHANTED_BOOK
      points: 100
      requirements:
        - "1x Enchanted Book (Smite V)"
      required-items:
        - ENCHANTED_BOOK:1:SMITE:5
      reward:
        material: ENCHANTED_BOOK
        name: "Smite VI"
        enchants:
          - SMITE:6
    bane-of-arthropods-6:
      name: "Bane of Arthropods VI"
      icon: ENCHANTED_BOOK
      points: 100
      requirements:
        - "1x Enchanted Book (Bane of Arthropods V)"
      required-items:
        - ENCHANTED_BOOK:1:BANE_OF_ARTHROPODS:5
      reward:
        material: ENCHANTED_BOOK
        name: "Bane of Arthropods VI"
        enchants:
          - BANE_OF_ARTHROPODS:6
    knockback-3:
      name: "Knockback III"
      icon: ENCHANTED_BOOK
      points: 100
      requirements:
        - "1x Enchanted Book (Knockback II)"
      required-items:
        - ENCHANTED_BOOK:1:KNOCKBACK:2
      reward:
        material: ENCHANTED_BOOK
        name: "Knockback III"
        enchants:
          - KNOCKBACK:3
    fire-aspect-3:
      name: "Fire Aspect III"
      icon: ENCHANTED_BOOK
      points: 100
      requirements:
        - "1x Enchanted Book (Fire Aspect II)"
      required-items:
        - ENCHANTED_BOOK:1:FIRE_ASPECT:2
      reward:
        material: ENCHANTED_BOOK
        name: "Fire Aspect III"
        enchants:
          - FIRE_ASPECT:3
    looting-4:
      name: "Looting IV"
      icon: ENCHANTED_BOOK
      points: 100
      requirements:
        - "1x Enchanted Book (Looting III)"
      required-items:
        - ENCHANTED_BOOK:1:LOOTING:3
      reward:
        material: ENCHANTED_BOOK
        name: "Looting IV"
        enchants:
          - LOOTING:4
    sweeping-edge-4:
      name: "Sweeping Edge IV"
      icon: ENCHANTED_BOOK
      points: 100
      requirements:
        - "1x Enchanted Book (Sweeping Edge III)"
      required-items:
        - ENCHANTED_BOOK:1:SWEEPING_EDGE:3
      reward:
        material: ENCHANTED_BOOK
        name: "Sweeping Edge IV"
        enchants:
          - SWEEPING_EDGE:4
    fortune-4:
      name: "Fortune IV"
      icon: ENCHANTED_BOOK
      points: 100
      requirements:
        - "1x Enchanted Book (Fortune III)"
      required-items:
        - ENCHANTED_BOOK:1:FORTUNE:3
      reward:
        material: ENCHANTED_BOOK
        name: "Fortune IV"
        enchants:
          - FORTUNE:4
    power-6:
      name: "Power VI"
      icon: ENCHANTED_BOOK
      points: 100
      requirements:
        - "1x Enchanted Book (Power V)"
      required-items:
        - ENCHANTED_BOOK:1:POWER:5
      reward:
        material: ENCHANTED_BOOK
        name: "Power VI"
        enchants:
          - POWER:6
    punch-3:
      name: "Punch III"
      icon: ENCHANTED_BOOK
      points: 100
      requirements:
        - "1x Enchanted Book (Punch II)"
      required-items:
        - ENCHANTED_BOOK:1:PUNCH:2
      reward:
        material: ENCHANTED_BOOK
        name: "Punch III"
        enchants:
          - PUNCH:3
    luck-of-the-sea-4:
      name: "Luck of the Sea IV"
      icon: ENCHANTED_BOOK
      points: 100
      requirements:
        - "1x Enchanted Book (Luck of the Sea III)"
      required-items:
        - ENCHANTED_BOOK:1:LUCK_OF_THE_SEA:3
      reward:
        material: ENCHANTED_BOOK
        name: "Luck of the Sea IV"
        enchants:
          - LUCK_OF_THE_SEA:4
    lure-4:
      name: "Lure IV"
      icon: ENCHANTED_BOOK
      points: 100
      requirements:
        - "1x Enchanted Book (Lure III)"
      required-items:
        - ENCHANTED_BOOK:1:LURE:3
      reward:
        material: ENCHANTED_BOOK
        name: "Lure IV"
        enchants:
          - LURE:4
    loyalty-4:
      name: "Loyalty IV"
      icon: ENCHANTED_BOOK
      points: 100
      requirements:
        - "1x Enchanted Book (Loyalty III)"
      required-items:
        - ENCHANTED_BOOK:1:LOYALTY:3
      reward:
        material: ENCHANTED_BOOK
        name: "Loyalty IV"
        enchants:
          - LOYALTY:4
    impaling-6:
      name: "Impaling VI"
      icon: ENCHANTED_BOOK
      points: 100
      requirements:
        - "1x Enchanted Book (Impaling V)"
      required-items:
        - ENCHANTED_BOOK:1:IMPALING:5
      reward:
        material: ENCHANTED_BOOK
        name: "Impaling VI"
        enchants:
          - IMPALING:6
    riptide-4:
      name: "Riptide IV"
      icon: ENCHANTED_BOOK
      points: 100
      requirements:
        - "1x Enchanted Book (Riptide III)"
      required-items:
        - ENCHANTED_BOOK:1:RIPTIDE:3
      reward:
        material: ENCHANTED_BOOK
        name: "Riptide IV"
        enchants:
          - RIPTIDE:4
    quick-charge-4:
      name: "Quick Charge IV"
      icon: ENCHANTED_BOOK
      points: 100
      requirements:
        - "1x Enchanted Book (Quick Charge III)"
      required-items:
        - ENCHANTED_BOOK:1:QUICK_CHARGE:3
      reward:
        material: ENCHANTED_BOOK
        name: "Quick Charge IV"
        enchants:
          - QUICK_CHARGE:4
    piercing-5:
      name: "Piercing V"
      icon: ENCHANTED_BOOK
      points: 100
      requirements:
        - "1x Enchanted Book (Piercing IV)"
      required-items:
        - ENCHANTED_BOOK:1:PIERCING:4
      reward:
        material: ENCHANTED_BOOK
        name: "Piercing V"
        enchants:
          - PIERCING:5
    thorns-4:
      name: "Thorns IV"
      icon: ENCHANTED_BOOK
      points: 100
      requirements:
        - "1x Enchanted Book (Thorns III)"
      required-items:
        - ENCHANTED_BOOK:1:THORNS:3
      reward:
        material: ENCHANTED_BOOK
        name: "Thorns IV"
        enchants:
          - THORNS:4
    soul-speed-4:
      name: "Soul Speed IV"
      icon: ENCHANTED_BOOK
      points: 100
      requirements:
        - "1x Enchanted Book (Soul Speed III)"
      required-items:
        - ENCHANTED_BOOK:1:SOUL_SPEED:3
      reward:
        material: ENCHANTED_BOOK
        name: "Soul Speed IV"
        enchants:
          - SOUL_SPEED:4
    swift-sneak-4:
      name: "Swift Sneak IV"
      icon: ENCHANTED_BOOK
      points: 100
      requirements:
        - "1x Enchanted Book (Swift Sneak III)"
      required-items:
        - ENCHANTED_BOOK:1:SWIFT_SNEAK:3
      reward:
        material: ENCHANTED_BOOK
        name: "Swift Sneak IV"
        enchants:
          - SWIFT_SNEAK:4
    lunge-4:
      name: "Lunge IV"
      icon: ENCHANTED_BOOK
      points: 100
      requirements:
        - "1x Enchanted Book (Lunge III)"
      required-items:
        - ENCHANTED_BOOK:1:LUNGE:3
      reward:
        material: ENCHANTED_BOOK
        name: "Lunge IV"
        enchants:
          - LUNGE:4
    density-6:
      name: "Density VI"
      icon: ENCHANTED_BOOK
      points: 100
      requirements:
        - "1x Enchanted Book (Density V)"
      required-items:
        - ENCHANTED_BOOK:1:DENSITY:5
      reward:
        material: ENCHANTED_BOOK
        name: "Density VI"
        enchants:
          - DENSITY:6
    breach-5:
      name: "Breach V"
      icon: ENCHANTED_BOOK
      points: 100
      requirements:
        - "1x Enchanted Book (Breach IV)"
      required-items:
        - ENCHANTED_BOOK:1:BREACH:4
      reward:
        material: ENCHANTED_BOOK
        name: "Breach V"
        enchants:
          - BREACH:5
    wind-burst-4:
      name: "Wind Burst IV"
      icon: ENCHANTED_BOOK
      points: 100
      requirements:
        - "1x Enchanted Book (Wind Burst III)"
      required-items:
        - ENCHANTED_BOOK:1:WIND_BURST:3
      reward:
        material: ENCHANTED_BOOK
        name: "Wind Burst IV"
        enchants:
          - WIND_BURST:4
    night-vision-helmet:
      slot: 15
      name: "Night Vision Helmet"
      icon: NETHERITE_HELMET
      points: 80
      requirements:
        - "1x Netherite Helmet"
      required-items:
        - NETHERITE_HELMET:1
      required-potions:
        - NIGHT_VISION:1
      reward:
        material: NETHERITE_HELMET
        name: "Night Vision Helmet"
        custom-id: night-vision-helmet
        effect:
          type: NIGHT_VISION
          amplifier: 0
    jump-boots:
      slot: 16
      name: "Jump Boost Boots"
      icon: NETHERITE_BOOTS
      points: 80
      requirements:
        - "1x Netherite Boots"
      required-items:
        - NETHERITE_BOOTS:1
      required-potions:
        - LEAPING:1
      reward:
        material: NETHERITE_BOOTS
        name: "Jump Boost Boots"
        custom-id: jump-boots
        effect:
          type: JUMP_BOOST
          amplifier: 1
    speed-leggings:
      slot: 17
      name: "Speed Leggings"
      icon: NETHERITE_LEGGINGS
      points: 80
      requirements:
        - "1x Netherite Leggings"
      required-items:
        - NETHERITE_LEGGINGS:1
      required-potions:
        - SWIFTNESS:1
      reward:
        material: NETHERITE_LEGGINGS
        name: "Speed Leggings"
        custom-id: speed-leggings
        effect:
          type: SPEED
          amplifier: 0
    elytra-chestplate:
      slot: 22
      name: "Elytra Chestplate"
      icon: NETHERITE_CHESTPLATE
      points: 200
      requirements:
        - "1x Netherite Chestplate"
        - "1x Elytra"
      required-items:
        - NETHERITE_CHESTPLATE:1
        - ELYTRA:1
      reward:
        material: NETHERITE_CHESTPLATE
        name: "Elytra Chestplate"
        custom-id: elytra-chestplate
        glider: true
        lore:
          - "Can be used as an elytra"
